# Base URL
@baseUrl = http://localhost:3000

###
# ***************************************************** TEST FOR TEAM C ************************************************************
GET {{baseUrl}}/find/3pm-server-MECAZON/users
Content-Type: application/json

###
GET {{baseUrl}}/find/3pm-server-MECAZON/employees
Content-Type: application/json

###
GET {{baseUrl}}/find/3pm-client-MECAZON/products
Content-Type: application/json


###
@userId = 6762122c98aa42a8912e4107

GET {{baseUrl}}/retrieve-user/3pm-server-MECAZON/users/{{userId}}
Content-Type: application/json

###
@productId = 6762101591082b735a40df8d

POST {{baseUrl}}/add-to-cart/3pm-server-MECAZON/users/{{userId}}/{{productId}}
Content-Type: application/json

###
# Insert a single Product
POST {{baseUrl}}/insert/3pm-server-MECAZON/users
Content-Type: application/json

{
    "document": {
        "name": "Apple",
        "price": 1.99
    }
}

###

# Insert users
POST {{baseUrl}}/add-user/3pm-server-MECAZON/users
Content-Type: application/json

{
    "document": {
        "name.first_name": "test",
        "name.last_name": "test",
        "location.country": "United States",
        "location.city": "",
        "location.address": "",
        "location.zip_code": "",
        "contact_info.email": "west-mecsantiago@gmail.com",
        "contact_info.phone_number": "000-000-0000",
        "password": "toolet",
        "orders": ["keyboard", "mouse", "sticky notes"],
        "payment_type": ""
    }
}


###
# Insert employees
POST {{baseUrl}}/add-employee/3pm-server-MECAZON/employees
Content-Type: application/json

{
    "document": {
        "username": "Admin",
        "name.first_name": "Bob",
        "name.last_name": "Bartholomew III Senior",
        "password": "admin",
        "department": "CEO",
        "employment_type": "full-time",
        "isAdmin": "true",
        "contact_info.email": "west-mecadmin@gmail.com",
        "contact_info.phone_number": "123-456-789",
        "contact_info.address": "5632 W Mecazon Dr Glendale AZ"
    }
}


###
# Insert a single Product
POST {{baseUrl}}/insert/3pm-client-MECAZON/products
Content-Type: application/json

{
    "document": {
        "item": "Backpack",
        "category": "Educational Supplies",
        "price_in_usd": 38,
        "details": "JanSport student backpack solid black, two large compartments",
        "product_img": "https://drive.google.com/file/d/1B7u-3AzklqIB_6NIvdJ0xhuuRxMSXPtk/view?usp=drive_link",
        "__v": 0,
        "colorArr": ["red", "white", "blue", "green"]
    }
}

###

# Insert multiple users
POST {{baseUrl}}/insert/3pm-server-MECAZON/employees
Content-Type: application/json

{
    "documents": [
        {
            "username": "jane_doe",
            "email": "jane@example.com"
        },
        {
            "username": "john_smith",
            "email": "john@example.com"
        }
    ]
}




# Test DELETE /delete/:database/:collection/:id
###
# Delete a User (Replace {user_id} with an actual ID)
DELETE {{baseUrl}}/delete/3pm-server-MECAZON/users/{user_id}
Content-Type: application/json


###
# Delete a User (Replace {user_id} with an actual ID)
DELETE {{baseUrl}}/delete/3pm-server-MECAZON/employees/{user_id}
Content-Type: application/json



# ***************************************************** TEST FOR TEAM C ************************************************************


###
# Test POST /insert/:database/:collection
###
# Insert a single Product
POST {{baseUrl}}/insert/productsDB/products
Content-Type: application/json

{
    "document": {
        "name": "Apple",
        "price": 1.99
    }
}

###

# Insert multiple users
POST {{baseUrl}}/insert/usersemployeesDB/users
Content-Type: application/json

{
    "documents": [
        {
            "username": "jane_doe",
            "email": "jane@example.com"
        },
        {
            "username": "john_smith",
            "email": "john@example.com"
        }
    ]
}

###

###
# Test PUT /update/:database/:collection/:id
###
# Update a Product (Replace {product_id} with an actual ID)
PUT {{baseUrl}}/update/productsDB/products/{product_id}
Content-Type: application/json

{
    "update": {
        "price": 2.49
    }
}

###
@id=676210b991082b735a40df94
# Delete a User (Replace {user_id} with an actual ID)
DELETE {{baseUrl}}/delete/3pm-client-MECAZON/products/{{id}}
Content-Type: application/json